apiVersion: v1
kind: ReplicationController
metadata:
  name: answers-app-universal
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: answers-app
        type: universal
    spec:
      containers:
      - name: universal
        image: us.gcr.io/angular-mobile/answers-app-universal:v1458166754
        ports:
        - containerPort: 3000
